import type { Metadata } from "next"
import { Nunito } from "next/font/google"

import { ClerkProvider } from "@clerk/nextjs"
import { ptBR } from "@clerk/localizations"

import { Toaster } from "@/components/ui/sonner"

import "./globals.css"
import { ExitModal } from "@/components/modals/exit-modal"

const font = Nunito({
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Lingo",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider localization={ptBR}>
      <html lang="pt-BR">
        <body className={`${font.className} antialiased`}>
          <Toaster />
          <ExitModal />
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
